-- Seed client-supplied tag list (from tags.docx, June 2026 client feedback)
-- and seed the new "about_assassination" site_content key.
-- ON CONFLICT DO NOTHING keeps this migration idempotent across re-runs.

INSERT INTO tags (slug, name_ar, name_en) VALUES
  ('marines',                    'المارينز',                     'Marines'),
  ('lebanon',                    'لبنان',                        'Lebanon'),
  ('invasion',                   'اجتياح',                       'Invasion'),
  ('1982',                       '1982',                         '1982'),
  ('camp-david',                 'كامب ديفد',                    'Camp David'),
  ('egypt',                      'مصر',                          'Egypt'),
  ('sadat',                      'السادات',                      'Sadat'),
  ('egypt-detentions',           'اعتقالات مصر',                 'Egypt Detentions'),
  ('bazzeq',                     'بزيق',                         'Bazzeq'),
  ('arab-summit',                'قمة عربية',                    'Arab Summit'),
  ('summits',                    'قمم',                          'Summits'),
  ('arab-regimes',               'الأنظمة العربية',              'Arab Regimes'),
  ('fatima',                     'فاطمة',                        'Fatima'),
  ('fatima-husband',             'زوج فاطمة',                    'Fatima''s Husband'),
  ('palestine-loyalty-lebanon',  'وفاء فلسطين للبنان',           'Palestine''s Loyalty to Lebanon'),
  ('sheikhs',                    'شيوخ',                         'Sheikhs'),
  ('the-toiler',                 'الكادح',                       'The Toiler'),
  ('palestinian-factions',       'فصائل فلسطينية',               'Palestinian Factions'),
  ('abu-ammar',                  'أبو عمار',                     'Abu Ammar'),
  ('abu-musa',                   'أبو موسى',                     'Abu Musa'),
  ('plo',                        'منظمة التحرير',                'PLO'),
  ('split',                      'انشقاق',                       'Split'),
  ('infighting',                 'اقتتال',                       'Infighting'),
  ('fatah',                      'فتح',                          'Fatah'),
  ('jerusalem',                  'القدس',                        'Jerusalem'),
  ('the-zionist',                'الصهيوني',                     'The Zionist'),
  ('zionist-soldier',            'الجندي الصهيوني',              'The Zionist Soldier'),
  ('khawarna',                   'خوارنة',                       'Khawarna'),
  ('keffiyeh',                   'الكوفية',                      'Keffiyeh'),
  ('women-tag',                  'المرأة',                       'Women'),
  ('armed-struggle',             'الكفاح المسلح',                'Armed Struggle'),
  ('fedayeen',                   'الفدائي',                      'Fedayeen'),
  ('exit-beirut',                'الخروج من بيروت',              'Exit from Beirut'),
  ('massacres',                  'المذابح',                      'Massacres'),
  ('the-camp',                   'المخيم',                       'The Camp'),
  ('christ',                     'المسيح',                       'Christ'),
  ('residents',                  'المقيمون',                     'The Residents'),
  ('the-left',                   'اليسار',                       'The Left'),
  ('beirut',                     'بيروت',                        'Beirut'),
  ('kuwaiti-affairs',            'شؤون كويتية',                  'Kuwaiti Affairs'),
  ('censorship',                 'الرقابة',                      'Censorship'),
  ('press-freedom',              'حرية الإعلام',                 'Press Freedom'),
  ('united-nations',             'الأمم المتحدة',                'United Nations'),
  ('usa',                        'الولايات المتحدة',             'USA'),
  ('oil',                        'النفط',                        'Oil'),
  ('normalization',              'التطبيع',                      'Normalization'),
  ('self-rule',                  'الحكم الذاتي',                 'Self-Rule'),
  ('settlement',                 'التسوية',                      'The Settlement'),
  ('zionist-leaders',            'قادة صهاينة',                  'Zionist Leaders'),
  ('trucks',                     'الشاحنات',                     'The Trucks'),
  ('pflp',                       'الجبهة الشعبية لتحرير فلسطين', 'PFLP'),
  ('george-habash',              'جورج حبش',                     'George Habash'),
  ('lebanese-resistance',        'المقاومة اللبنانية',           'Lebanese Resistance'),
  ('the-south',                  'الجنوب',                       'The South'),
  ('book-fair',                  'معرض الكتاب',                  'Book Fair'),
  ('sidon',                      'صيدا',                         'Sidon'),
  ('tyre',                       'صور',                          'Tyre'),
  ('palestinian-bourgeoisie',    'البرجوازية الفلسطينية',        'Palestinian Bourgeoisie'),
  ('climate-crisis',             'أزمة المناخ',                  'Climate Crisis'),
  ('kamal-jumblatt',             'كمال جنبلاط',                  'Kamal Jumblatt'),
  ('sectarianism',               'الطائفية',                     'Sectarianism'),
  ('three-nos',                  'اللاءات الثلاث',               'The Three No''s'),
  ('freedom-opinion',            'حرية الرأي',                   'Freedom of Opinion'),
  ('surrender',                  'استسلام',                      'Surrender'),
  ('the-press',                  'الصحافة',                      'The Press'),
  ('conferences',                'مؤتمرات',                      'Conferences'),
  ('abu-saleh-nimr',             'أبو صالح النمر',               'Abu Saleh Al-Nimr'),
  ('phalangists',                'الكتائب',                      'Phalangists'),
  ('reagan',                     'ريجان',                        'Reagan'),
  ('handala-face',               'وجه حنظلة',                    'Handala''s Face'),
  ('islamic-summit',             'القمة الإسلامية',              'Islamic Summit'),
  ('soviet-union',               'الاتحاد السوفييتي',            'Soviet Union'),
  ('non-alignment',              'عدم الانحياز',                 'Non-Alignment'),
  ('rapid-deployment-force',     'قوات التدخل السريع',           'Rapid Deployment Force'),
  ('cold-war',                   'الحرب الباردة',                'Cold War'),
  ('thatcher',                   'تاتشر',                        'Thatcher'),
  ('begin',                      'بيغن',                         'Begin'),
  ('pope-shenouda',              'البابا شنودة',                 'Pope Shenouda'),
  ('syria',                      'سوريا',                        'Syria'),
  ('sudan',                      'السودان',                      'Sudan'),
  ('al-assad',                   'الأسد',                        'Al-Assad'),
  ('reactor-bombing',            'قصف المفاعل',                  'Reactor Bombing'),
  ('philip-habib',               'فيليب حبيب',                   'Philip Habib')
ON CONFLICT (slug) DO NOTHING;

-- Editable site content for the new "عن الاغتيال" page.
-- Hard-coded defaults live in app/[locale]/about-assassination/page.tsx so the
-- page still renders if this row is deleted or never inserted.
INSERT INTO site_content (key, title_ar, title_en, content_ar, content_en) VALUES
  ('about_assassination',
   'عن الاغتيال',
   'The Assassination',
   E'في الثاني والعشرين من يوليو/تموز 1987، تعرّض ناجي العلي لمحاولة اغتيال في لندن قرب مكتب جريدة "القبس" التي كان يعمل فيها، حيث أُطلقت رصاصة على رأسه. ظلّ في غيبوبة خمسة أسابيع، ثم رحل في التاسع والعشرين من أغسطس/آب من العام نفسه.\n\nاغتيل ناجي العلي لأن ريشته رفضت أن تنحاز إلا لمن هم "تحت"، ولأنه كان يكتب ويرسم بصدقٍ عارٍ، لا يجامل نظاماً ولا فصيلاً ولا قبيلة. اختار حنظلة – الطفل اللاجئ – أن يدير ظهره للعالم، فردّ العالم بطلقةٍ غادرة.\n\nلم يُغلق ملف الاغتيال حتى اليوم. لم يُعرف القاتل علناً، ولم تُكشف الجهة التي خطّطت للجريمة. ما يُعرف أن صوته كان يزعج كثيرين، وأن رصاصةً واحدة لم تستطع أن تُسكته: رسومه ما زالت تُتداول، وحنظلة ما زال هناك، شاهداً صامتاً، ينتظر العودة.',
   E'On 22 July 1987, Naji Al-Ali was shot in the head outside the London office of Al-Qabas, the Kuwaiti newspaper he worked for. He remained in a coma for five weeks and died on 29 August 1987.\n\nHe was assassinated because his pen refused to side with anyone but the dispossessed — those he called the people "underneath". He flattered no regime, no faction, no tribe. His character Handala, the refugee child, turned his back on the world; the world replied with a bullet.\n\nThe case has never been publicly resolved. The shooter has not been named, and the parties who planned the killing have never been identified. What is known is that his voice troubled many, and that a single bullet did not silence him: his cartoons are still in circulation, and Handala is still there — a silent witness, waiting for the return.')
ON CONFLICT (key) DO NOTHING;
